title: Augustin 'Gus' Burchell
email: augustin.burchell@gmail.com
description: Personal website of a student and creator
name: Augustin Burchell
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
future: true
