title: Augustin 'Gus' Burchell
email: augustin.burchell@gmail.com
description: Personal website of an aspiring prolific-creator and apprehensive technologist.
name: Augustin Burchell
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
future: true
