title: Augustin 'Gus' Burchell
email: augustin.burchell@gmail.com
description: Personal website of a soon-to-be-former student and aspirational creator
name: Augustin Burchell
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
future: true
